"""Integration tests: exercise the real pipelines end-to-end. Each test skips
itself when its external tools are missing, so the suite passes (with skips)
on a bare host and fully runs inside the Docker image."""
import os
import shutil
import subprocess

import pytest

from dcmaker.core.budget import byte_ceiling
from dcmaker.core.service import ConvertRequest, convert

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLES = os.path.join(os.path.dirname(HERE), "samples", "original")

need_ffmpeg = pytest.mark.skipif(
    not (shutil.which("ffmpeg") and shutil.which("ffprobe")),
    reason="ffmpeg/ffprobe not on PATH")
need_gifsicle = pytest.mark.skipif(
    not shutil.which("gifsicle"), reason="gifsicle not on PATH")


def _has_libwebp() -> bool:
    if not shutil.which("ffmpeg"):
        return False
    try:
        out = subprocess.run(["ffmpeg", "-hide_banner", "-encoders"],
                             capture_output=True, text=True).stdout
        return "libwebp" in out
    except Exception:
        return False


need_libwebp = pytest.mark.skipif(
    not _has_libwebp(), reason="ffmpeg built without libwebp")


def _has_svg_renderer() -> bool:
    if shutil.which("rsvg-convert"):
        return True
    try:
        import cairosvg  # noqa: F401
        return True
    except ImportError:
        return False


def _has_chromium() -> bool:
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as pw:
            return bool(pw.chromium.executable_path
                        and os.path.exists(pw.chromium.executable_path))
    except Exception:
        return False


@pytest.fixture
def anim_gif(tmp_path):
    """Tiny 1s animated GIF fixture generated by ffmpeg."""
    path = str(tmp_path / "anim.gif")
    subprocess.run(
        ["ffmpeg", "-y", "-v", "error", "-f", "lavfi",
         "-i", "testsrc=size=64x64:rate=8:duration=1", str(path)],
        check=True, capture_output=True)
    return path


@need_ffmpeg
@need_gifsicle
def test_gif_to_emoji_gif(anim_gif, tmp_path):
    out = str(tmp_path / "emoji.gif")
    r = convert(ConvertRequest(anim_gif, preset="emoji", out=out))
    assert r.path == out and os.path.isfile(out)
    assert (r.width, r.height) == (128, 128)
    assert r.size <= byte_ceiling(256)
    assert r.frames > 1


@need_ffmpeg
@need_libwebp
def test_gif_to_emoji_webp(anim_gif, tmp_path):
    out = str(tmp_path / "emoji.webp")
    r = convert(ConvertRequest(anim_gif, preset="emoji", fmt="webp", out=out))
    assert r.path == out and os.path.isfile(out)
    assert r.fmt == "webp"
    assert (r.width, r.height) == (128, 128)
    assert r.size <= byte_ceiling(256)
    assert r.frames > 1                       # ffprobe confirms it animates
    # RIFF container tagged WEBP
    magic = open(out, "rb").read(12)
    assert magic[:4] == b"RIFF" and magic[8:12] == b"WEBP"


@need_ffmpeg
def test_gif_to_sticker_apng(anim_gif, tmp_path):
    out = str(tmp_path / "sticker.png")
    r = convert(ConvertRequest(anim_gif, preset="sticker", fmt="apng", out=out))
    assert (r.width, r.height) == (320, 320)
    assert r.size <= byte_ceiling(512)
    # APNG signature: PNG magic + acTL chunk
    blob = open(out, "rb").read()
    assert blob[:8] == b"\x89PNG\r\n\x1a\n" and b"acTL" in blob


@need_ffmpeg
@pytest.mark.skipif(not _has_svg_renderer(), reason="no SVG renderer")
def test_static_svg_to_sticker_png(tmp_path):
    src = os.path.join(SAMPLES, "star_static.svg")
    out = str(tmp_path / "static.png")
    r = convert(ConvertRequest(src, preset="sticker", out=out))
    assert (r.width, r.height) == (320, 320)
    assert r.frames == 1 and r.fmt == "png"
    assert r.size <= byte_ceiling(512)


@need_ffmpeg
@need_gifsicle
@pytest.mark.skipif(not _has_chromium(), reason="chromium not installed")
def test_animated_svg_to_sticker_gif(tmp_path):
    src = os.path.join(SAMPLES, "star_spin.svg")
    out = str(tmp_path / "spin.gif")
    r = convert(ConvertRequest(src, preset="sticker", out=out))
    assert (r.width, r.height) == (320, 320)
    assert r.size <= byte_ceiling(512)
    assert r.frames > 1
    # duration auto-detected from the 2s loop -> ~2s of frames captured
    assert any("captured" in n for n in r.notes)


@need_ffmpeg
def test_static_input_refuses_gif_format(tmp_path):
    src = os.path.join(SAMPLES, "star_static.svg")
    with pytest.raises(ValueError, match="nothing to animate"):
        convert(ConvertRequest(src, fmt="gif", out=str(tmp_path / "x.gif")))
